### PR TITLE
Feature/publicscripts

### PR DESCRIPTION
**Pull request by galvin-SH**
in process, the same functionality is represented in home.js's 2nd fetch call as in the Ticket model's afterCreate hook. I couldn't get either to work so its in both places atm

### CODE REVIEW

**Review by n810tran — COMMENTED** [review]
approved

**Comment by galvin-SH** [comment]
i'll push the conflict resolution in a minute

**Comment by galvin-SH** [comment]
uhhhh something broke, cant even start server anymore

**Comment by galvin-SH** [comment]
reverting to pre-merge branch

**Pull request closed without merging**
